name: Echo Message

on: [push,workflow_dispatch]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v7

        - name: first job
          run: echo "first job"
          
    Second_job:
        - name: Second Job
          run: echo "Second Job"
        